CREATE TABLE IF NOT EXISTS AUTH(
	id UUID PRIMARY KEY,
	email VARCHAR(50),
	password VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS EVENT(
	id VARCHAR(30) PRIMARY KEY,
	user_id UUID,
	title VARCHAR(50),
	date VARCHAR(15),
	location VARCHAR(50),
	FOREIGN KEY (user_id) REFERENCES AUTH(id)
);

DO $$ BEGIN
	CREATE TYPE BUDGET_TYPE AS ENUM('INCOME', 'EXPENSE');
EXCEPTION
	WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS BUDGET(
	id VARCHAR(30) PRIMARY KEY,
	event_id VARCHAR(30),
	description VARCHAR(30),
	amount VARCHAR(30),
	budget_type BUDGET_TYPE,
	FOREIGN KEY (event_id) REFERENCES EVENT(id)
);